# -*- coding: utf-8 -*-
"""sql visualization_data

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Gwxp0rxCfmU2o9C90qgJQEjTBSArx-Ta
"""

#install necessary libraries
!pip install -q xlrd
!pip install -q bokeh
import xlrd
import pandas as pd
from google.colab import files


#grab fertlity and urban population excel docs from https://www.gapminder.org/data/
fert_url = 'https://docs.google.com/spreadsheet/pub?key=phAwcNAVuyj0TAlJeCEzcGQ&output=xlsx'
pop_url = 'https://docs.google.com/spreadsheet/pub?key=phAwcNAVuyj0XOoBL_n5tAQ&output=xlsx'

#import files
fertility = pd.read_excel(fert_url, sheet_name = 'Data', header = 0, index_col = False)
population = pd.read_excel(pop_url, sheet_name = 'Data', header = 0, index_col = False)

# need tranpose columns
fertility.set_index('Total fertility rate', inplace=True)
population.set_index('Total population', inplace=True)

trans_fert = fertility.transpose()
trans_pop = population.transpose()

#reset indices
trans_fert = trans_fert.reset_index()
trans_pop = trans_pop.reset_index()

#melt data frame and drop na values
melt_fert = pd.melt(trans_fert, id_vars = 'index', var_name = 'Country', value_name = 'Fertility')
melt_pop = pd.melt(trans_pop, id_vars = 'index', var_name = 'Country', value_name = 'Population')
melt_fert = melt_fert.dropna()
melt_pop = melt_pop.dropna()


#reset indexes prior to merging data frames
melt_fert = melt_fert.set_index('index')
melt_pop = melt_pop.set_index('index')

#rename indices
melt_fert.index.names = ['Year']
melt_pop.index.names = ['Year']
melt_fert = melt_fert.reset_index().dropna()
melt_pop = melt_pop.reset_index().dropna()

print(melt_fert.head())
print(melt_pop.head())


# export files to csvs to be merged within sql

"""
#melt_fert.to_csv('gap_fert.csv',sep=",", index=False)
files.download('gap_fert.csv')

#melt_pop.to_csv('gap_pop.csv', sep=",", index=False)
files.download('gap_pop.csv')
"""

